name: 'package-action'
on: # rebuild any PRs and main branch changes
  pull_request:
#   push:
#     branches:
#       - main
#       - 'releases/*'
  workflow_dispatch:
  release: 

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write  
    steps:
      # - name: Checking out!
      #  uses: actions/checkout@v3
        # with:
        #   ref: 'Give optional branch name/SHA/tag to checkout' 
  
      # The ORAS cli, possibly will be baked in runner-vm and this step will not be required
      - name: Install Oras
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.12.0_*.tar.gz oras-install/
          echo "Oras installed!"
      
      - name: Create a file
        run: |
          touch README.md
          
      - name: Running action   
        uses: ruchika-jain/package-action@1.0.1
        with:
          package-name: 'oras-test'
        id: publish-action
        
      - uses: sigstore/cosign-installer@main
        
      - name: Sign the images
        run: |
          cosign sign \
            ghcr.io/srahul3/oras_test:1.0.0
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Verify the pushed tags
        run: cosign verify ghcr.io/srahul3/oras_test:1.0.0
        env:
          COSIGN_EXPERIMENTAL: 1
