name: 'cosign keyless sig'
on: # rebuild any PRs and main branch changes
  pull_request:
#   push:
#     branches:
#       - main
#       - 'releases/*'
  workflow_dispatch:
  release: 

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write    
    steps:
      # - name: Checking out!
      #  uses: actions/checkout@v2
        # with:
        #   ref: 'Give optional branch name/SHA/tag to checkout' 
  
      - name: Create a file since checkout has issue with sigstore/cosign-installer@main
        run: |
          touch README.md
          
      # The ORAS cli, possibly will be baked in runner-vm and this step will not be required
      - name: Install Oras
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.12.0_*.tar.gz oras-install/
          echo "Oras installed!"
          
      - name: Running action   
        run: |        
          oras login ghcr.io -u srahul3 -p ${{ secrets.GITHUB_TOKEN }}
          oras push ghcr.io/srahul3/oras:1.0.0 \
          --manifest-config /dev/null:application/vnd.actions.packages \
          ./:application/vnd.actions.packages.layer.v1+tar
          
      - uses: sigstore/cosign-installer@main
      
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_REPOSITORY: "ghcr.io/${{ github.repository_owner }}/signatures"
        run: |          
          echo "Y" | sudo -S cosign sign \
          -a "repo=${{ github.repository }}" \
          -a "workflow=${{ github.workflow }}" \
          -a "ref=${{ github.sha }}" \
          ghcr.io/${{ github.repository_owner }}/oras:1.0.0

      - name: Verify the pushed tags
        run: cosign verify ghcr.io/srahul3/oras:1.0.0
        env:
          COSIGN_EXPERIMENTAL: 1
